spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.xvlvpqmrtxvxxzkpxhqs
    password: Surayu@6299
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    cache:
      type: none

  data:
    redis:
      repositories:
        enabled: false

  session:
    store-type: none

logging:
  level:
    com.gymora: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
