spring:
  datasource:
    url: jdbc:postgresql://ep-tiny-pond-ao4nwbyv-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_LYpz4MOGTxN3
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 6000

logging:
  level:
    com.gymora: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
